In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

def feature_changing(x_train):

    feature_names = ['internet', 'sex', 'traveltime', 'studytime', 'freetime', 'absences', 'age', 'iq']
    
    X_train_df = pd.DataFrame(x_train, columns=feature_names)
    
    # Identify categorical features from the datsaet
    categorical_features = ['internet', 'sex']
    
    label_encoders = {}
    
    # Perform label encoding
    for feature in categorical_features:
        le = LabelEncoder()
        X_train_df[feature] = le.fit_transform(X_train_df[feature])
        label_encoders[feature] = le
    
    x_train_encoded = X_train_df.values
    
    return x_train_encoded


In [3]:

data = pd.read_excel('Training data.xlsx')
x_train = np.array(data.iloc[:,0:8])
y_train = np.array(data.iloc[:,8]).reshape(-1,1)

x_train = feature_changing(x_train)

In [4]:
print(x_train[:5])

[[0 1 2 2 5 6 18 118]
 [1 1 2 2 2 7 19 107]
 [1 1 3 3 3 5 18 108]
 [0 0 3 3 4 9 17 100]
 [1 1 1 4 3 4 19 96]]


In [6]:
def z_score(x_train):
  
  x_mean = np.mean(x_train, axis=0)
  
  x_std = np.std(x_train, axis=0)
  
  x_train_scaled = (x_train - x_mean) / x_std


  return x_train_scaled,x_std,x_mean

In [7]:
def cost(x_train,y_train,w,b):
  
  m = x_train.shape[0]
  
  predictions = x_train.dot(w) + b
  
  loss = np.sum((predictions - y_train) ** 2) / (2 * m)


  return loss

In [8]:
import numpy as np

def gradient_descent(x_train, y_train, w, b, learning_rate=0.01, num_iterations=10):
    m = x_train.shape[0]  
    
    for i in range(num_iterations):
        
        predictions = x_train.dot(w) + b
        
        
        dw = (1/m) * x_train.T.dot(predictions - y_train)
        db = (1/m) * np.sum(predictions - y_train)
        
        
        w = w - learning_rate * dw
        b = b - learning_rate * db
        
    return w, b


In [9]:
x_train = x_train.astype(np.float64)
x_train,x_std,x_mean = z_score(x_train)

np.random.seed(2147483647)
w = np.random.randn(x_train.shape[1],1)
b = np.random.randn(1)

old_cost = 0

while abs(old_cost - cost(x_train,y_train,w,b))>0.00001:
  old_cost = cost(x_train,y_train,w,b)
  w,b = gradient_descent(x_train,y_train,w,b)

x_predict = pd.read_excel('Test data.xlsx').iloc[:,:8].to_numpy()
x_predict = feature_changing(x_predict)
x_predict = (x_predict - x_mean)/x_std
ans = pd.read_excel('Test data.xlsx').iloc[:,8].to_numpy()

y_predict = np.dot(x_predict,w) + b

accuracy = 0
for dim in range(len(ans)):
  if abs(y_predict[dim]-ans[dim])<0.5:
    accuracy += 1
accuracy = round(accuracy*100/200.0,2)
ok = 'Congratulations' if accuracy>95 else 'Optimization required'
print(f"{ok}, your accuracy is {accuracy}%")

Congratulations, your accuracy is 100.0%
